"""Markdown/text artifact generation."""

from __future__ import annotations

from typing import Any

from arctic_analytics import __version__
from arctic_analytics.artifacts.citation import citation_doi
from arctic_analytics.artifacts.extractors import extract_generated_code
from arctic_analytics.artifacts.models import ResearchSession


def render_methods(session: ResearchSession) -> str:
    trace = session.analysis_trace.data or {}
    model = trace.get("model") or "not recorded"
    code_snippets = extract_generated_code(trace)
    metadata_names = ", ".join(_dataset_names(session)) or "not recorded"
    prompt = session.prompt or trace.get("prompt_str") or "not recorded"

    return f"""# Draft Methods

Analyses were supported by Arctic Analytics v{__version__}, experimental open-source research software for metadata-aware, inspectable, constrained AI-assisted analysis over structured data.

The analysis workflow used an agent to review structured-data context before producing inspectable Python tool calls. The context supplied to the agent included dataset metadata, data dictionary information, summary statistics when available, and a researcher-provided prompt.

## Analysis Question

{prompt}

## Data And Context

Datasets represented in the exported context bundle: {metadata_names}.

## Agent And Model

Model recorded in the trace: {model}.

## Execution Summary

The artifact bundle includes the exported analysis trace, prompts, generated code snippets, tool outputs, and limitations. Generated Python was intended for application-level constrained execution and human review. The bundle contains {len(code_snippets)} generated code snippet(s).

## Human Review

This methods draft is generated for review and publication support. Researchers should verify that the metadata, generated code, outputs, and final claims match the source data and intended analysis before citing or publishing results.
"""


def render_software_citation() -> str:
    doi = citation_doi()
    doi_text = f" (DOI: {doi})" if doi else ""
    return f"""# Software Citation

Analyses were performed using Arctic Analytics v{__version__}{doi_text}. (See `citation.cff` for full citation metadata.)

Please cite the software using the repository `CITATION.cff` metadata and verify that the cited release, package version, and Zenodo record refer to the same version.
"""


def render_limitations(session: ResearchSession) -> str:
    trace = session.analysis_trace.data or {}
    limitations = trace.get("limitations") or [
        "Artifact bundles package existing analysis inputs and outputs; they do not prove correctness.",
        "The MVP bundle export is not a deterministic replay system.",
        "Model outputs may vary across time, model versions, and provider behavior.",
        "Execution restrictions are application-level constraints, not OS-level isolation.",
    ]
    lines = ["# Limitations", ""]
    lines.extend(f"- {item}" for item in limitations)
    lines.append("")
    return "\n".join(lines)


def render_bundle_readme(session: ResearchSession) -> str:
    trace_note = (
        "This bundle includes an Arctic Analytics analysis trace."
        if session.analysis_trace.available
        else "No analysis trace was provided; generated code and model outputs may be unavailable."
    )
    return f"""# Arctic Analytics Research Bundle

This directory contains publication-support artifacts generated by Arctic Analytics v{__version__}.

{trace_note}

## Contents

- `analysis_trace.json`: exported analysis trace or an unavailable marker.
- `run_manifest.json`: lightweight run metadata and selected SHA-256 hashes when source content is available.
- `context_bundle.json`: dataset metadata, researcher notes, assumptions, and source file references.
- `prompts.json`: system/user prompt material available from the exported session.
- `methods.md`: draft methods text for human review.
- `generated_code/`: generated Python snippets extracted from tool calls.
- `figures/`: decoded figures when image payloads are available.
- `outputs/`: tool outputs and final answer material.
- `environment.json`: local software/runtime metadata.
- `citation.cff` and `software_citation.md`: software citation metadata and suggested citation wording.
- `limitations.md`: known limitations for reproducibility and interpretation.
"""


def _dataset_names(session: ResearchSession) -> list[str]:
    context = session.context_bundle.data
    names: list[str] = []

    metadata = context.get("dataset_metadata")
    if isinstance(metadata, dict):
        names.extend(str(name) for name in metadata.keys())

    sample_metadata = context.get("metadata")
    if isinstance(sample_metadata, dict) and sample_metadata.get("dataset_name"):
        names.append(str(sample_metadata["dataset_name"]))

    return sorted(set(names))
