import streamlit as st
import logging

def render_data_analyst_prompt_guide():
    logging.info(f'render_data_analyst_prompt_guide - {st.session_state["session_id"]}')

    with st.sidebar.expander(':blue[Pompting Guide]'):
        st.write("""Arctic Analytics is really good at filtering, aggregating and calculating KPIs from your data. Follow this guide to get the most out of Arctic Analytics:
1. Make sure you provided a good dataset description and a short description of each column in your dataset. This will help Arctic Analytics understand your data better.
2. Arctic Analytics performs best when you outline the steps the AI should take to answer your question. For example, if you want to know the average sales for each product category, you should provide the AI with the following prompt: :green[Group the data by category and calculate the average sales].
3. If you want to filter your data, make sure you provide the AI with the filter conditions. For example, if you want to know the average sales for each product category in the year 2020, you should provide the AI with the following prompt: :green[Filter the data for the year 2020, group the data by category and calculate the average sales].
4. If you want the AI to calculate a KPI like discount percentage, make sure you provide the AI with the formula to calculate the KPI. For example, if you want to know the discount percentage for each product category, you should provide the AI with the following prompt: :green[Group the data by category and calculate the discount percentage as (discount/sales)*100].
5. Finally, if the AI is not able to answer your question, try simplifying your prompt and/or providing more context to the AI.
""")
        st.info('Be sure to QA the python syntax generated by Arctic Analytics')

def render_analytics_agent_prompt_guide():
    logging.info(f'render_analytics_agent_prompt_guide - {st.session_state["session_id"]}')
    
    with st.sidebar.expander(':blue[Analytics Agent Prompt Guide]'):
        st.write("""Arctic Analytics is really good at filtering, aggregating and calculating KPIs from your data. Follow this guide to get the most out of Arctic Analytics:
1. Make sure you provided a good dataset description and a short description of each column in your dataset. This will help Arctic Analytics understand your data better.
2. Arctic Analytics performs best when you outline the steps the AI should take to answer your question. For example, if you want to know the average sales for each product category, you should provide the AI with the following prompt: :green[Group the data by category and calculate the average sales].
3. If you want to filter your data, make sure you provide the AI with the filter conditions. For example, if you want to know the average sales for each product category in the year 2020, you should provide the AI with the following prompt: :green[Filter the data for the year 2020, group the data by category and calculate the average sales].
4. If you want the AI to calculate a KPI like discount percentage, make sure you provide the AI with the formula to calculate the KPI. For example, if you want to know the discount percentage for each product category, you should provide the AI with the following prompt: :green[Group the data by category and calculate the discount percentage as (discount/sales)*100].
5. Finally, if the AI is not able to answer your question, try simplifying your prompt and/or providing more context to the AI.
""")
        st.info('Be sure to QA the tool_calls made by Arctic Analytics')
